/* global describe, it, expect -- Jest globals (the Expo ESLint config only declares them for TypeScript) */
const {
  addSceneManifest,
  adoptSceneLifecycle,
  SCENE_MANIFEST,
} = require('../withIOSSceneLifecycle');

// `ios/ROAM/AppDelegate.swift` as generated by `expo prebuild` on SDK 57 (Linking overrides trimmed).
const SDK57_APP_DELEGATE = `internal import Expo
import React
import ReactAppDependencyProvider

@main
class AppDelegate: ExpoAppDelegate {
  var window: UIWindow?

  var reactNativeDelegate: ExpoReactNativeFactoryDelegate?
  var reactNativeFactory: RCTReactNativeFactory?

  public override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
  ) -> Bool {
    let delegate = ReactNativeDelegate()
    let factory = ExpoReactNativeFactory(delegate: delegate)
    delegate.dependencyProvider = RCTAppDependencyProvider()

    reactNativeDelegate = delegate
    reactNativeFactory = factory

#if os(iOS) || os(tvOS)
    window = UIWindow(frame: UIScreen.main.bounds)
    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions)
#endif

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  // Linking API
  public override func application(
    _ app: UIApplication,
    open url: URL,
    options: [UIApplication.OpenURLOptionsKey: Any] = [:]
  ) -> Bool {
    return super.application(app, open: url, options: options) || RCTLinkingManager.application(app, open: url, options: options)
  }
}
`;

describe('addSceneManifest', () => {
  it('declares one application scene handled by SceneDelegate', () => {
    const plist = addSceneManifest({ CFBundleName: 'ROAM' });
    expect(plist.CFBundleName).toBe('ROAM');
    expect(plist.UIApplicationSceneManifest).toEqual(SCENE_MANIFEST);
    const scenes =
      plist.UIApplicationSceneManifest.UISceneConfigurations.UIWindowSceneSessionRoleApplication;
    expect(scenes).toHaveLength(1);
    expect(scenes[0].UISceneDelegateClassName).toBe('$(PRODUCT_MODULE_NAME).SceneDelegate');
  });

  it('is idempotent and keeps an existing manifest', () => {
    const once = addSceneManifest({});
    expect(addSceneManifest(once)).toEqual(once);
    const custom = { UIApplicationSceneManifest: { UIApplicationSupportsMultipleScenes: true } };
    expect(addSceneManifest(custom)).toBe(custom);
  });
});

describe('adoptSceneLifecycle', () => {
  const adopted = adoptSceneLifecycle(SDK57_APP_DELEGATE);

  it('makes AppDelegate provide the React Native factory', () => {
    expect(adopted).toContain(
      'class AppDelegate: ExpoAppDelegate, ExpoReactNativeFactoryProvider {',
    );
    expect(adopted).toContain('reactNativeFactory = factory');
  });

  it('leaves window creation and React Native start to the scene delegate', () => {
    expect(adopted).not.toContain('UIWindow(frame:');
    expect(adopted).not.toContain('startReactNative');
    expect(adopted).toContain(
      'return super.application(application, didFinishLaunchingWithOptions: launchOptions)',
    );
  });

  it('keeps the Linking overrides (ExpoAppSceneDelegate dedupes them)', () => {
    expect(adopted).toContain('RCTLinkingManager.application(app, open: url, options: options)');
  });

  it('is idempotent', () => {
    expect(adoptSceneLifecycle(adopted)).toBe(adopted);
    expect(adopted.match(/ExpoReactNativeFactoryProvider/g)).toHaveLength(1);
  });

  it('refuses an AppDelegate it does not recognize', () => {
    expect(() => adoptSceneLifecycle('class AppDelegate: UIResponder {}')).toThrow(/not found/);
    const customWindow = SDK57_APP_DELEGATE.replace('#if os(iOS) || os(tvOS)\n', '');
    expect(() => adoptSceneLifecycle(customWindow)).toThrow(/unrecognized window creation/);
  });
});
